pipeline {
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
        GIT_REPO_NAME = "Jenkins"
        GIT_USER_NAME = "Thakur156"
    }
    
    stages {
        
        stage('Checkout') {
            steps {
                echo 'Checking out the code'
            }
        }

        stage('Build Docker and Push') {
        environment {
        DOCKER_IMAGE = "abhishekf5/cicd-e2e:${BUILD_NUMBER}"
        // DOCKERFILE_LOCATION = "python-jenkins-argocd-k8s/deploy/Dockerfile"
        REGISTRY_CREDENTIALS = credentials('docker-cred')
      }
            steps {
                script {
                    sh 'cd python-jenkins-argocd-k8s && docker build -t ${DOCKER_IMAGE} .'
            def dockerImage = docker.image("${DOCKER_IMAGE}")
            docker.withRegistry('https://index.docker.io/v1/', "docker-cred") {
                dockerImage.push()
                }
            }
        }
        }
        
        stage('Update K8S manifest & push to Repo') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
                        sh '''
                        git config user.email "aliisrar156@gmail.com.com"
                        git config user.name "thakur156"
                        BUILD_NUMBER=${BUILD_NUMBER}
                        sed -i "s/v1/${BUILD_NUMBER}/g" python-jenkins-argocd-k8s/deploy/deploy.yaml
                        git add python-jenkins-argocd-k8s/deploy/deploy.yaml
                        git commit -m "Update deployment image to version ${BUILD_NUMBER}"
                        git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
                        '''
                    }
                }
            }
        }
    }
}



