pipeline {
  agent any
  stages {
    stage('build') {
      steps {
        echo 'Building the application...'
      }
    }
    stage('test') {
      when {
        expression {
          BRANCH_NAME == 'main'
        }
      }
      steps {
        echo 'Testing the application...'
      }
    }
    stage('deploy') {
      steps {
        echo 'Deploying the application...'
      }
    }
  }
  post {
    always {
      echo 'I dont know'
    }
    success {
      echo 'It is successful'
    }
    failure {
      echo 'It is failure'
    }
  }
}

