pipeline {
  agent any
  stages {
    stage('build') {
      steps {
        echo 'Building the application...'
      }
    }
    stage('test') {
      when{
        expression {
          BRANCH_NAME == 'main'
        }
      }
      steps {
        echo 'Testing the application...'
      }
    }
    stage('deploy') {
      steps {
        echo 'Deploying the application...'
      }
    }
  }
  post{
    always{
      echo'i dont know'
    }
    success{
      echo'it is successful'
    }
    failure{
      echo'it is failure'
    }
  }
}

